CREATE TABLE empleado
(
	id SERIAL PRIMARY KEY, -- AUTOGENERATED
	nombres VARCHAR(100) NOT NULL,
	apellidos VARCHAR(100) NOT NULL,
	cedula VARCHAR(100) NOT NULL,
	correo VARCHAR(100) NOT NULL,
	telefono VARCHAR(8) NOT NULL,
	cargo VARCHAR(100) NOT NULL,
	departamento VARCHAR(100) NOT NULL,
	salario NUMERIC(10, 2) NOT NULL,
	fechaContratacion DATE NOT NULL,
	estado VARCHAR(50)


);

-- Agregar registros a la tabla de libros
INSERT INTO empleado
(nombres, apellidos, cedula, correo, telefono, cargo, departamento, salario, fechaContratacion, estado)
VALUES
('Carlos Alberto', 'Martinez Lopez', '001-120398-1001A', 'carlos.martinez@gmail.com', '88881234', 'Administrador', 'Administracion', 25000.00, '2022-03-15', 'Activo'),

('Maria Fernanda', 'Gomez Ruiz', '001-230499-1002B', 'maria.gomez@gmail.com', '77774567', 'Contadora', 'Contabilidad', 28000.00, '2021-06-10', 'Activo'),

('Jose Antonio', 'Perez Garcia', '001-180597-1003C', 'jose.perez@gmail.com', '88885678', 'Desarrollador', 'Tecnologia', 35000.00, '2023-01-20', 'Activo'),

('Ana Sofia', 'Lopez Castillo', '001-050700-1004D', 'ana.lopez@gmail.com', '77778901', 'Recepcionista', 'Administracion', 18000.00, '2024-02-05', 'Activo'),

('Luis Enrique', 'Hernandez Diaz', '001-110695-1005E', 'luis.hernandez@gmail.com', '88889012', 'Supervisor', 'Produccion', 30000.00, '2020-08-17', 'Activo'),

('Daniela Alejandra', 'Torres Mendoza', '001-270201-1006F', 'daniela.torres@gmail.com', '77771234', 'Analista', 'Recursos Humanos', 26000.00, '2023-05-12', 'Activo'),

('Kevin Andres', 'Ramirez Flores', '001-160899-1007G', 'kevin.ramirez@gmail.com', '88882345', 'Tecnico', 'Soporte', 22000.00, '2022-11-01', 'Activo'),

('Sofia Isabel', 'Castro Morales', '001-090298-1008H', 'sofia.castro@gmail.com', '77773456', 'Gerente', 'Ventas', 45000.00, '2019-04-22', 'Activo'),

('Fernando Jose', 'Rojas Sanchez', '001-210596-1009J', 'fernando.rojas@gmail.com', '88884567', 'Vendedor', 'Ventas', 20000.00, '2024-06-03', 'Activo'),

('Gabriela Maria', 'Mendoza Ortiz', '001-301100-1010K', 'gabriela.mendoza@gmail.com', '77775678', 'Asistente', 'Recursos Humanos', 19500.00, '2025-01-13', 'Activo');

SELECT * FROM empleado